import { PULL_TABLE_ORDER, type SyncEngine } from '@baraka/sync-engine';
export { PULL_TABLE_ORDER };
export declare const ensureDeviceRegistered: SyncEngine['ensureDeviceRegistered'];
export declare const ensureInvoiceRange: SyncEngine['ensureInvoiceRange'];
export declare const nextInvoiceNumber: SyncEngine['nextInvoiceNumber'];
export declare const isDeviceRegistered: SyncEngine['isDeviceRegistered'];
export declare const pullTableV2: SyncEngine['pullTableV2'];
export declare const enqueueOutbox: SyncEngine['enqueueOutbox'];
export declare const flushOutbox: SyncEngine['flushOutbox'];
export declare const retryDeadLetters: SyncEngine['retryDeadLetters'];
export declare const backfillOutboxOnce: SyncEngine['backfillOutboxOnce'];
export declare const getSyncStatus: SyncEngine['getSyncStatus'];
